services:
  postgres:
    image: postgres:16-alpine
    container_name: chenow_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chenow_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chenow_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    volumes:
      - ./backend/public/upload:/app/public/upload
    depends_on:
      - postgres
    networks:
      - chenow_network

volumes:
  postgres_data:

networks:
  chenow_network:
    driver: bridge
